//! TurboWorkflow types: definition (JSON) and runtime state (persisted per session).

use chrono::{DateTime, Utc};
use serde::{Deserialize, Serialize};

/// Single step in a workflow definition.
#[derive(Debug, Clone, Serialize, Deserialize, PartialEq, Eq)]
#[serde(rename_all = "snake_case")]
pub struct WorkflowStepDef {
    pub id: String,
    /// Step type: "llm" (run model to complete task) or "user_input" (wait for user reply).
    #[serde(rename = "type")]
    pub step_type: String,
    /// For llm: task description. For user_input: prompt shown to user.
    #[serde(default)]
    pub description: String,
    /// For user_input: key under which to store the user's reply in workflow inputs.
    #[serde(default)]
    pub input_key: Option<String>,
}

/// Workflow input parameter (name, optional description, optional default).
#[derive(Debug, Clone, Serialize, Deserialize, Default, PartialEq, Eq)]
#[serde(rename_all = "snake_case")]
pub struct WorkflowInputDef {
    #[serde(default)]
    pub name: String,
    #[serde(default)]
    pub description: String,
    #[serde(default)]
    pub default: Option<String>,
}

/// Workflow definition (generated by LLM or provided by user). Persisted with state.
#[derive(Debug, Clone, Serialize, Deserialize, PartialEq, Eq)]
#[serde(rename_all = "snake_case")]
pub struct WorkflowDef {
    #[serde(default)]
    pub id: String,
    #[serde(default)]
    pub name: String,
    #[serde(default)]
    pub description: String,
    #[serde(default)]
    pub inputs: Vec<WorkflowInputDef>,
    pub steps: Vec<WorkflowStepDef>,
}

impl WorkflowDef {
    /// Validate: at least one step; step types are "llm" or "user_input"; user_input steps have input_key.
    pub fn validate(&self) -> Result<(), String> {
        if self.steps.is_empty() {
            return Err("workflow must have at least one step".to_string());
        }
        for (i, s) in self.steps.iter().enumerate() {
            let t = s.step_type.to_lowercase();
            if t != "llm" && t != "user_input" {
                return Err(format!("step {}: type must be 'llm' or 'user_input'", i));
            }
            if t == "user_input" && s.input_key.as_deref().unwrap_or("").trim().is_empty() {
                return Err(format!(
                    "step {} (user_input): input_key is required",
                    i
                ));
            }
        }
        Ok(())
    }
}

/// Runtime status of a workflow instance.
#[derive(Debug, Clone, Copy, Serialize, Deserialize, PartialEq, Eq, Default)]
#[serde(rename_all = "snake_case")]
pub enum WorkflowStatus {
    #[default]
    Running,
    WaitingUserInput,
    Paused,
    Completed,
    Failed,
    Cancelled,
    /// Step was waiting for user input and timed out.
    WaitingTimeout,
}

/// Persisted workflow state (one per session). Written after each step.
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(rename_all = "snake_case")]
pub struct WorkflowState {
    pub workflow_id: String,
    pub session_key: String,
    pub status: WorkflowStatus,
    pub current_step_index: usize,
    /// Initial + user-provided inputs (keys from WorkflowInputDef.name and step input_key).
    #[serde(default)]
    pub inputs: std::collections::HashMap<String, String>,
    /// Output of each completed step (indexed by step index).
    #[serde(default)]
    pub step_outputs: Vec<String>,
    pub created_at: DateTime<Utc>,
    pub updated_at: DateTime<Utc>,
    pub user_input_timeout_secs: u64,
    /// Inline workflow definition so we can resume without loading separately.
    pub definition: WorkflowDef,
}

impl WorkflowState {
    pub fn new(
        session_key: String,
        definition: WorkflowDef,
        initial_inputs: std::collections::HashMap<String, String>,
        user_input_timeout_secs: u64,
    ) -> Self {
        let now = Utc::now();
        let workflow_id = definition.id.clone();
        if workflow_id.is_empty() {
            // allow empty id; we could generate one
        }
        Self {
            workflow_id: if workflow_id.is_empty() {
                format!("wf-{}", now.timestamp())
            } else {
                workflow_id
            },
            session_key,
            status: WorkflowStatus::Running,
            current_step_index: 0,
            inputs: initial_inputs,
            step_outputs: Vec::new(),
            created_at: now,
            updated_at: now,
            user_input_timeout_secs,
            definition,
        }
    }

    pub fn current_step(&self) -> Option<&WorkflowStepDef> {
        self.definition.steps.get(self.current_step_index)
    }

    pub fn is_finished(&self) -> bool {
        matches!(
            self.status,
            WorkflowStatus::Completed
                | WorkflowStatus::Failed
                | WorkflowStatus::Cancelled
                | WorkflowStatus::WaitingTimeout
        )
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use std::collections::HashMap;

    #[test]
    fn workflow_status_default_is_running() {
        assert_eq!(WorkflowStatus::default(), WorkflowStatus::Running);
    }

    #[test]
    fn workflow_status_serialization_roundtrip() {
        for status in [
            WorkflowStatus::Running,
            WorkflowStatus::WaitingUserInput,
            WorkflowStatus::Completed,
            WorkflowStatus::Failed,
        ] {
            let json = serde_json::to_string(&status).unwrap();
            let parsed: WorkflowStatus = serde_json::from_str(&json).unwrap();
            assert_eq!(status, parsed);
        }
    }

    #[test]
    fn workflow_def_validate_empty_steps_rejected() {
        let def = WorkflowDef {
            id: String::new(),
            name: String::new(),
            description: String::new(),
            inputs: vec![],
            steps: vec![],
        };
        assert!(def.validate().is_err());
    }

    #[test]
    fn workflow_def_validate_llm_step_ok() {
        let def = WorkflowDef {
            id: "w1".to_string(),
            name: String::new(),
            description: String::new(),
            inputs: vec![],
            steps: vec![WorkflowStepDef {
                id: "s1".to_string(),
                step_type: "llm".to_string(),
                description: "Task".to_string(),
                input_key: None,
            }],
        };
        assert!(def.validate().is_ok());
    }

    #[test]
    fn workflow_def_validate_user_input_requires_input_key() {
        let def = WorkflowDef {
            id: String::new(),
            name: String::new(),
            description: String::new(),
            inputs: vec![],
            steps: vec![WorkflowStepDef {
                id: "s1".to_string(),
                step_type: "user_input".to_string(),
                description: "Wait".to_string(),
                input_key: None,
            }],
        };
        assert!(def.validate().is_err());
    }

    #[test]
    fn workflow_def_validate_user_input_with_key_ok() {
        let def = WorkflowDef {
            id: String::new(),
            name: String::new(),
            description: String::new(),
            inputs: vec![],
            steps: vec![WorkflowStepDef {
                id: "s1".to_string(),
                step_type: "user_input".to_string(),
                description: "Wait".to_string(),
                input_key: Some("reply".to_string()),
            }],
        };
        assert!(def.validate().is_ok());
    }

    #[test]
    fn workflow_state_new_empty_id_gets_generated() {
        let def = WorkflowDef {
            id: String::new(),
            name: String::new(),
            description: String::new(),
            inputs: vec![],
            steps: vec![WorkflowStepDef {
                id: "s1".to_string(),
                step_type: "llm".to_string(),
                description: "".to_string(),
                input_key: None,
            }],
        };
        let state = WorkflowState::new("sk".to_string(), def, HashMap::new(), 30);
        assert!(!state.workflow_id.is_empty());
        assert!(state.workflow_id.starts_with("wf-"));
    }

    #[test]
    fn workflow_state_current_step_and_is_finished() {
        let def = WorkflowDef {
            id: "w1".to_string(),
            name: String::new(),
            description: String::new(),
            inputs: vec![],
            steps: vec![
                WorkflowStepDef {
                    id: "s1".to_string(),
                    step_type: "llm".to_string(),
                    description: "".to_string(),
                    input_key: None,
                },
                WorkflowStepDef {
                    id: "s2".to_string(),
                    step_type: "llm".to_string(),
                    description: "".to_string(),
                    input_key: None,
                },
            ],
        };
        let state = WorkflowState::new("sk".to_string(), def.clone(), HashMap::new(), 30);
        assert_eq!(state.current_step_index, 0);
        assert!(!state.is_finished());
        let step = state.current_step().unwrap();
        assert_eq!(step.id, "s1");
    }
}
